name: delivery_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  hydrated_bloc: ^10.1.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  injectable: ^2.5.1
  get_it: ^8.3.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  injectable_generator: ^2.5.1

  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home_food/
    - assets/images/categories/
    - assets/images/food_details/
    - assets/images/misc/
    - assets/icons/
    - assets/fonts/
    - assets/fonts/Poppins/
    - assets/images/branding/
    - assets/data/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800

# flutter_assets:
#   assets_path: assets/images/
#   output_path: lib/assets/
#   filename: images.dart
#   field_prefix:
# flutter_assets:
#   assets_path: assets/icons/
#   output_path: lib/assets/
#   filename: icons.dart
#   field_prefix:
# flutter_assets:
#   assets_path: assets/data/
#   output_path: lib/assets/
#   filename: data.dart
#   field_prefix:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/branding/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/branding/splash_screen.png"
  android_12:
    image: "assets/images/branding/splash_screen.png"
    icon_background_color: "#ffffff"
  fullscreen: true
